# Generated by Django 5.2.14 on 2026-06-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event_faq_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='clients/')),
            ],
        ),
        migrations.CreateModel(
            name='CounterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text="e.g., '36' or '15'", max_length=20)),
                ('suffix', models.CharField(blank=True, help_text="e.g., '+' or 'k'", max_length=10, null=True)),
                ('title', models.CharField(max_length=100)),
                ('delay', models.CharField(default='0ms', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('icon_class', models.CharField(help_text="e.g., 'flaticon-verify'", max_length=50)),
                ('page', models.CharField(default='home1', help_text="e.g., 'home1_services'", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FrontendSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Internal name, e.g., 'Home 1 About'", max_length=100)),
                ('identifier', models.CharField(help_text="e.g., 'home1_about'", max_length=50, unique=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('button_text', models.CharField(blank=True, max_length=50, null=True)),
                ('button_link', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='frontend/')),
                ('video_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
