# Generated by Django 5.2.14 on 2026-06-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_clientlogo_counteritem_featureitem_frontendsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text="e.g., 'abc' for '/abc/'", unique=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='custom_pages/')),
                ('content', models.TextField(help_text='HTML content for the page')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
