# Generated by Django 5.2.14 on 2026-06-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_custompage'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='text',
            field=models.TextField(blank=True, help_text='Extra paragraph text for the banner', null=True),
        ),
    ]
