# Generated by Django 5.2.14 on 2026-06-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_banner_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='logo_text',
            field=models.CharField(blank=True, help_text="Text to display if Logo Type is 'Text Logo'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='logo_type',
            field=models.CharField(choices=[('image', 'Image Logo'), ('text', 'Text Logo')], default='image', max_length=10),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='settings/'),
        ),
    ]
