# Generated by Django 5.2.14 on 2026-06-17 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitesetting_logo_text_sitesetting_logo_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('identifier', models.CharField(help_text='e.g. main_nav, footer_nav_1', max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='copyright_text',
            field=models.CharField(default='Copyright 2026, All Right Reserved', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_about_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_newsletter_button_link',
            field=models.CharField(blank=True, default='#', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_newsletter_button_text',
            field=models.CharField(blank=True, default='Free Signup', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_newsletter_text',
            field=models.TextField(blank=True, default='Need to train your team? We offer flexible, cost-effective group memberships for your business, school', null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_newsletter_title',
            field=models.CharField(default='Newsletter', max_length=100),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(help_text='e.g. /about/ or https://google.com', max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.menu')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.menuitem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
