# Generated by Django 5.2.14 on 2026-06-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_menu_sitesetting_copyright_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.CharField(max_length=50)),
                ('is_recurring', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(help_text="e.g. '$09', 'Free'", max_length=20)),
                ('duration', models.CharField(help_text="e.g. '/month', '/year'", max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10)),
                ('features', models.TextField(help_text='Enter one feature per line')),
                ('is_featured', models.BooleanField(default=False, help_text='Highlight this plan (e.g. Enterprise)')),
                ('button_text', models.CharField(default='Get started', max_length=50)),
                ('button_link', models.CharField(default='#', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='copyright_text',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='footer_about_text',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='footer_newsletter_button_link',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='footer_newsletter_button_text',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='footer_newsletter_text',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='footer_newsletter_title',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
