# Generated by Django 5.2.14 on 2026-06-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text='e.g. enroll_now, read_more, submit, subscribe', max_length=50, unique=True)),
                ('text', models.CharField(help_text='The actual text shown on the button', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Button Settings',
            },
        ),
    ]
