# Generated by Django 5.2.14 on 2026-06-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_buttonsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontendsection',
            name='extra_text',
            field=models.CharField(blank=True, help_text='e.g. Badge text or secondary subtitle', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='frontendsection',
            name='image_2',
            field=models.ImageField(blank=True, help_text='Secondary image if needed', null=True, upload_to='frontend/'),
        ),
        migrations.AddField(
            model_name='frontendsection',
            name='image_3',
            field=models.ImageField(blank=True, help_text='Tertiary image if needed', null=True, upload_to='frontend/'),
        ),
    ]
