# Generated by Django 5.2.14 on 2026-06-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_frontendsection_extra_text_frontendsection_image_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='map_url',
            field=models.URLField(blank=True, help_text='Google Maps Embed URL', null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='opening_hours',
            field=models.CharField(blank=True, help_text='e.g. Week Days: 09.00 to 18.00 Sunday: Closed', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
