# Generated by Django 5.2.14 on 2026-06-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_sitesetting_map_url_sitesetting_opening_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Build skills with courses flexible online courses', help_text='Use <br> for line breaks', max_length=255)),
                ('hero_subtitle', models.CharField(default='Learn latest skills', max_length=255)),
                ('hero_button_text', models.CharField(default='Join For free', max_length=50)),
                ('hero_button_link', models.CharField(default='/about/', max_length=255)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('about_heading', models.CharField(default='We Are Top <br> Online <span class="theme_color">Courses</span>', max_length=255)),
                ('about_text', models.TextField(default="The argument in favor of using filler text goes something like this: If you use real content in the Consulting Process, anytime you reach a review point you'll end up reviewing and negotiating the content itself and not the design.")),
                ('about_button_text', models.CharField(default='Discover More', max_length=50)),
                ('about_button_link', models.CharField(default='/about/', max_length=255)),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('video_heading', models.CharField(default='Explore Our <span class="theme_color">Video</span>', max_length=255)),
                ('video_subheading', models.CharField(default='Explore Online Courses', max_length=255)),
                ('video_url', models.URLField(default='https://www.youtube.com/watch?v=kxPCFljwJws')),
                ('video_bg_image', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('pricing_heading', models.CharField(default='Simple <span class="theme_color">Pricing</span>', max_length=255)),
                ('pricing_subheading', models.CharField(default='Pricing Package', max_length=255)),
                ('cta_heading', models.CharField(default='We Are The <br> Best <span class="theme_color">Education</span>', max_length=255)),
                ('cta_button_text', models.CharField(default='Register Now', max_length=50)),
                ('cta_button_link', models.CharField(default='/register/', max_length=255)),
            ],
            options={
                'verbose_name': 'Home Page Setting',
                'verbose_name_plural': 'Home Page Settings',
            },
        ),
    ]
