# Generated by Django 5.2.14 on 2026-06-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_homepagesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesetting',
            name='events_subtitle',
            field=models.CharField(default='Explore Event', max_length=255),
        ),
        migrations.AddField(
            model_name='homepagesetting',
            name='events_title',
            field=models.CharField(default='Our Upcoming Events', max_length=255),
        ),
        migrations.AddField(
            model_name='homepagesetting',
            name='explore_courses_text',
            field=models.TextField(default='Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat <br> nulla pariatur Duis aute irure dolor in reprehenderit in'),
        ),
        migrations.AddField(
            model_name='homepagesetting',
            name='explore_courses_title',
            field=models.CharField(default='You can learn anything, Explore <br> featured courses', max_length=255),
        ),
        migrations.AddField(
            model_name='homepagesetting',
            name='goal_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='home/'),
        ),
        migrations.AddField(
            model_name='homepagesetting',
            name='goal_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='home/'),
        ),
        migrations.AddField(
            model_name='homepagesetting',
            name='goal_subtitle',
            field=models.CharField(default='Achieve Goals', max_length=255),
        ),
        migrations.AddField(
            model_name='homepagesetting',
            name='goal_text',
            field=models.TextField(default='Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur Duis aute irure dolor in'),
        ),
        migrations.AddField(
            model_name='homepagesetting',
            name='goal_title',
            field=models.CharField(default='Start To Success', max_length=255),
        ),
        migrations.AddField(
            model_name='homepagesetting',
            name='instructor_button_link',
            field=models.CharField(default='/membership/', max_length=255),
        ),
        migrations.AddField(
            model_name='homepagesetting',
            name='instructor_button_text',
            field=models.CharField(default='Click here for apply', max_length=50),
        ),
        migrations.AddField(
            model_name='homepagesetting',
            name='instructor_image',
            field=models.ImageField(blank=True, null=True, upload_to='home/'),
        ),
        migrations.AddField(
            model_name='homepagesetting',
            name='instructor_text',
            field=models.TextField(default='Top instructors from around the world teach millions of students Duis aute irure dolor in <br> voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non'),
        ),
        migrations.AddField(
            model_name='homepagesetting',
            name='instructor_title',
            field=models.CharField(default='Become an instructor', max_length=255),
        ),
        migrations.AddField(
            model_name='homepagesetting',
            name='professional_button_link',
            field=models.CharField(default='#', max_length=255),
        ),
        migrations.AddField(
            model_name='homepagesetting',
            name='professional_button_text',
            field=models.CharField(default='Short courses', max_length=50),
        ),
        migrations.AddField(
            model_name='homepagesetting',
            name='professional_image',
            field=models.ImageField(blank=True, null=True, upload_to='home/'),
        ),
        migrations.AddField(
            model_name='homepagesetting',
            name='professional_subtitle',
            field=models.CharField(default='Learn anything', max_length=255),
        ),
        migrations.AddField(
            model_name='homepagesetting',
            name='professional_text',
            field=models.TextField(default='Position yourself for success with a variety of collegeclasses including general education courses'),
        ),
        migrations.AddField(
            model_name='homepagesetting',
            name='professional_title',
            field=models.CharField(default='Take online courses Earn <br> professional', max_length=255),
        ),
        migrations.AddField(
            model_name='homepagesetting',
            name='testimonials_subtitle',
            field=models.CharField(default='Testimonial', max_length=255),
        ),
        migrations.AddField(
            model_name='homepagesetting',
            name='testimonials_text',
            field=models.TextField(default='Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu <br> fugiat nulla pariatur Duis aute irure dolor in reprehenderit in'),
        ),
        migrations.AddField(
            model_name='homepagesetting',
            name='testimonials_title',
            field=models.CharField(default='Words From Customers', max_length=255),
        ),
    ]
