# Generated by Django 5.2.14 on 2026-06-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_homepagesetting_events_subtitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(default='Our mission is to provide <br> a free Online <br> Courses and Class', max_length=255)),
                ('banner_subtitle', models.CharField(default='About', max_length=255)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('banner_image_2', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('goal_subtitle', models.CharField(default='Achieve Goals', max_length=255)),
                ('goal_title', models.CharField(default='Start To Success', max_length=255)),
                ('goal_text', models.TextField(default='Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur Duis aute irure dolor in')),
                ('goal_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('skill_subtitle', models.CharField(default='Our Status valu', max_length=255)),
                ('skill_title', models.CharField(default='Differentiate your classroom <br> What makes us special?', max_length=255)),
                ('skill_text', models.TextField(default='Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur')),
                ('skill_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('professional_subtitle', models.CharField(default='Learn anything', max_length=255)),
                ('professional_title', models.CharField(default='Take online courses Earn <br> professional', max_length=255)),
                ('professional_text', models.TextField(default='Position yourself for success with a variety of collegeclasses including general education courses')),
                ('professional_button_text', models.CharField(default='Short courses', max_length=50)),
                ('professional_button_link', models.CharField(default='#', max_length=255)),
                ('professional_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('testimonials_subtitle', models.CharField(default='Testimonial', max_length=255)),
                ('testimonials_title', models.CharField(default='Words From Customers', max_length=255)),
                ('testimonials_text', models.TextField(default='Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu <br> fugiat nulla pariatur Duis aute irure dolor in reprehenderit in')),
                ('team_title', models.CharField(default='Our best online Techer', max_length=255)),
                ('team_text', models.TextField(default='Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur')),
                ('clients_title', models.CharField(default='Key supporters', max_length=255)),
                ('clients_text', models.TextField(default='These leading universities are currently offering online degree <br> courses on FutureLearn:')),
                ('contact_info_title', models.CharField(default='Contact us', max_length=255)),
                ('contact_info_text', models.TextField(default='It is a long established fact that a reader will be distracted by the readable content of a page')),
                ('contact_form_title', models.CharField(default='Visit us <br> for Free Resources', max_length=255)),
                ('contact_form_text', models.TextField(default='These leading universities are currently offering online degree courses on FutureLearn:')),
            ],
            options={
                'verbose_name': 'About Page Setting',
                'verbose_name_plural': 'About Page Settings',
            },
        ),
    ]
