# Generated by Django 5.2.14 on 2026-06-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_aboutpagesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_subtitle', models.CharField(default='Contact us', max_length=255)),
                ('banner_title', models.CharField(default='Contact Now', max_length=255)),
                ('banner_text', models.TextField(default='Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur Duis aute irure dolor in reprehenderit in')),
                ('info_subtitle', models.CharField(default='GET IN TOUCH', max_length=255)),
                ('info_title', models.CharField(default='Visit one of our agency locations <br> or contact us today', max_length=255)),
                ('info_text', models.TextField(default="We'd love to hear from you. Whether you have a question about our courses, pricing, or anything else, our team is ready to answer all your questions.")),
                ('form_title', models.CharField(default='Leave a message', max_length=255)),
                ('form_text', models.TextField(default='Please fill out the form below and we will get back to you as soon as possible.')),
                ('form_button_text', models.CharField(default='Send Message', max_length=50)),
            ],
            options={
                'verbose_name': 'Contact Page Setting',
                'verbose_name_plural': 'Contact Page Settings',
            },
        ),
    ]
