# Generated by Django 5.2.14 on 2026-06-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_contactpagesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpagesetting',
            name='goal_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
    ]
