# Generated by Django 5.2.14 on 2026-06-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_aboutpagesetting_goal_image_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesPageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_subtitle', models.CharField(default='Courses v1', max_length=255)),
                ('banner_title', models.CharField(default='Explore <br> Featured Courses', max_length=255)),
                ('banner_image_1', models.ImageField(blank=True, null=True, upload_to='courses/')),
                ('banner_image_2', models.ImageField(blank=True, null=True, upload_to='courses/')),
            ],
            options={
                'verbose_name': 'Courses Page Setting',
                'verbose_name_plural': 'Courses Page Settings',
            },
        ),
    ]
