# Generated by Django 5.2.14 on 2026-06-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_coursespagesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_subtitle', models.CharField(default='Blog default', max_length=200)),
                ('banner_title', models.CharField(default='Latest articles & news', max_length=200)),
                ('banner_text', models.TextField(default='Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur Duis aute irure dolor in reprehenderit in')),
                ('button_text', models.CharField(default='View More Artical', max_length=50)),
            ],
            options={
                'verbose_name': 'Blog Page Setting',
                'verbose_name_plural': 'Blog Page Settings',
            },
        ),
    ]
