# Generated by Django 5.2.14 on 2026-06-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_blogpagesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpagesetting',
            name='default_post_image',
            field=models.ImageField(blank=True, help_text='Fallback image for blog posts that do not have an image.', null=True, upload_to='blog/defaults/'),
        ),
    ]
