# Generated by Django 5.2.14 on 2026-06-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_blogpagesetting_default_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpagesetting',
            name='team_button_link',
            field=models.CharField(default='#', max_length=255),
        ),
        migrations.AddField(
            model_name='aboutpagesetting',
            name='team_button_text',
            field=models.CharField(default='View More', max_length=50),
        ),
        migrations.AddField(
            model_name='blogpagesetting',
            name='button_link',
            field=models.CharField(default='#', max_length=255),
        ),
    ]
