# Generated by Django 5.2.14 on 2026-06-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_aboutpagesetting_team_button_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Do not change this key once created, as it's used in HTML templates.", max_length=50, unique=True)),
                ('value', models.CharField(help_text='The actual text that will be displayed on the website.', max_length=255)),
                ('description', models.CharField(blank=True, help_text='Where is this label used?', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Site Label & Text',
                'verbose_name_plural': 'Site Labels & Texts',
                'ordering': ['key'],
            },
        ),
    ]
