# Generated by Django 5.2.14 on 2026-06-21 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_sitelabel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.CharField(help_text="e.g. '/' or '/about/'", max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('is_auth_required', models.BooleanField(default=False, help_text='Show only to logged in users (e.g. Profile)')),
                ('is_guest_only', models.BooleanField(default=False, help_text='Show only to logged out users (e.g. Login)')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.menuitem')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'ordering': ['order'],
            },
        ),
    ]
