# Generated by Django 5.2.14 on 2026-06-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_footercolumn_footerlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('percentage', models.IntegerField(help_text='Value between 0 and 100')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Skill Bar',
                'verbose_name_plural': 'Skill Bars',
                'ordering': ['order'],
            },
        ),
    ]
