# Generated by Django 5.2.14 on 2026-06-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_skillbar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g. 'Web Development Course' or 'General Inquiry'", max_length=200)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Contact Subject',
                'verbose_name_plural': 'Contact Subjects',
                'ordering': ['order'],
            },
        ),
    ]
