from django.urls import path
from django.views.generic import RedirectView
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('online-course-1/', views.online_course_1, name='online_course_1'),
    path('coaching/', views.coaching, name='coaching'),
    path('kindergarten/', views.kindergarten, name='kindergarten'),
    path('university/', views.university, name='university'),
    path('index.html', RedirectView.as_view(url='/', permanent=True)),
    path('course.html', RedirectView.as_view(url='/courses/', permanent=True)),
    path('blog.html', RedirectView.as_view(url='/blog/', permanent=True)),
    path('about.html', views.about, name='about'),
    path('about/', RedirectView.as_view(url='/about.html', permanent=True)),
    path('contact.html', views.contact, name='contact'),
    path('contact/', RedirectView.as_view(url='/contact.html', permanent=True)),
    path('faq.html', views.faq_list, name='faq'),
    path('faq/', RedirectView.as_view(url='/faq.html', permanent=True)),
    path('teacher.html', views.teacher_list, name='teacher'),
    path('teacher/', RedirectView.as_view(url='/teacher.html', permanent=True)),
    path('events/', views.event_list, name='event_list'),
    path('events/<slug:slug>/', views.event_detail, name='event_detail'),
    path('event.html', RedirectView.as_view(url='/events/', permanent=True)),
    path('membership/', views.membership, name='membership'),
    path('404/', views.not_found, name='not_found'),
    path('donation/', views.donation, name='donation'),
    path('profile/', views.profile, name='profile'),
    path('profile.html', RedirectView.as_view(url='/profile/', permanent=True)),
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('subscribe/', views.subscribe, name='subscribe'),
    path('<slug:slug>/', views.custom_page_detail, name='custom_page'),
]
