# Generated by Django 5.2.14 on 2026-06-18 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('side_text', models.CharField(blank=True, help_text='e.g. 5 lectures . 5 video', max_length=100, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CourseLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('time', models.CharField(blank=True, help_text='e.g. 10:25', max_length=50, null=True)),
                ('icon_class', models.CharField(default='fa-play-circle-o', help_text='e.g. fa-play-circle-o, fa-file-o, fa-file-word-o', max_length=50)),
                ('link', models.CharField(default='#', help_text='YouTube URL or # for document', max_length=500)),
                ('is_lightbox', models.BooleanField(default=True, help_text='Check if this is a video that should open in a popup')),
                ('order', models.PositiveIntegerField(default=0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='courses.coursemodule')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
