# Generated by Django 5.2.14 on 2026-06-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_coursereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='includes',
            field=models.TextField(blank=True, help_text='Comma or newline separated list of what the course includes', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='requirements',
            field=models.TextField(blank=True, help_text='Comma or newline separated list of requirements', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='what_you_will_learn',
            field=models.TextField(blank=True, help_text='Comma or newline separated list of things students will learn', null=True),
        ),
    ]
